query getIncident($id: Float!) {
  getIncident(id: $id) {
    message
    incident {
      id
      title
      description
      fromCustomer
      dueDate
      priority
      images
      reportImages
      reportMessage
      status
      employeeId
      employee {
        id
        name
        email
        avatar
      }
      reporterId
      reporter {
        id
        name
        email
        avatar
      }
      roomId
      room {
        id
        name
        floor
        thumbnail
      }
      incidentCategoryId
      incidentCategory {
        id
        name
        description
      }
      equipment {
        id
        name
        image
      }
      locationId
      location {
        name
        address
        thumbnail
      }
      createdAt
    }
  }
}
