query getLocationReservation($id: Float!) {
  getLocationReservation(id: $id) {
    message
    locationReservation {
      id
      totalCalculatedPrice
      status
      totalReceivedPrice
      startDate
      createdById
      createdBy {
        id
        name
        avatar
        email
      }
      locationId
      location {
        name
        images
      }
      createdAt
      updatedAt
    }
  }
}
