query getNotifications($input: GetNotificationsInput!) {
  getNotifications(input: $input) {
    page
    total
    totalPages
    message
    items {
      id
      content
      title
      dataId
      isRead
      image
      type
      userId
      createdAt
    }
  }
}
