query getRooms($input: GetRoomsInput!) {
  getRooms(input: $input) {
    page
    total
    totalPages
    message
    items {
      id
      name
      locationId
      description
      images
      thumbnail
      status
      basePrice
      locationId
      floor
      capacity
      users {
        name
        email
        avatar
      }
      createdAt
      updatedAt
    }
  }
}
